### ISSUE TITLE
0.1.3 release on PyPi contains invalid file

### ISSUE THREAD

**Issue by washeck** [bcb/apply_defaults#6]
[The 0.1.3 release on PyPi](https://files.pythonhosted.org/packages/d7/fc/87dcc12b6ec6a28fa794ba9e593c6af110c5ca013a63cb92ee303c98baec/apply_defaults-0.1.3.tar.gz) contains file `env.py` which is unused and does not have valid python syntax.

There is no visible impact in regular operation but it causes failure when you try to precompile your site-packages to bytecode using `compileall`. The file should not be present in the distribution .tgz.

**Comment by bcb** [comment]
Thanks for letting me know. I’ll remove it.
